spring:
  application:
    name: OnlineStore

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123123
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/master-changelog.yaml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 123123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate